// src/routes/generate.js
import express from 'express';
import Project from '../models/Project.js';
import { generateCode } from '../services/ai.js';
import { createZip } from '../services/zip.js';

const router = express.Router();

// Generate ZIP from project
router.post('/:projectId', async (req, res, next) => {
    try {
        const { projectId } = req.params;
        const token = req.headers.authorization?.split('Bearer ')[1];

        const project = await Project.findById(projectId);

        if (!project) {
            return res.status(404).json({ error: 'Project not found' });
        }

        // Check if user owns project or if it's public
        let isOwner = false;

        if (token) {
            try {
                const admin = (await import('../config/firebase.js')).default;
                const decodedToken = await admin.auth().verifyIdToken(token);
                isOwner = decodedToken.uid === project.userId;
            } catch (err) {
                // Token invalid, continue as guest
            }
        }

        if (!isOwner && !project.isPublic) {
            return res.status(403).json({ error: 'Access denied' });
        }

        // Prepare files object
        const files = {};
        const pages = project.pages && project.pages.length > 0
            ? project.pages
            : [{ name: 'Home', route: '/', layout: project.layout, id: 'default' }]; // Backward compatibility

        const generatedPages = [];

        // Create Route Map for Internal Linking
        const pageRouteMap = pages.reduce((acc, page) => {
            acc[page.id] = page.route;
            return acc;
        }, {});

        // Generate code for each page
        for (const page of pages) {
            const pageName = page.name || 'Page';
            const componentName = pageName.replace(/\s+/g, '');

            // Pass page layout and route map to AI
            const pageCode = await generateCode({ ...page, name: pageName }, project.theme, pageRouteMap);

            files[`src/pages/${componentName}.jsx`] = pageCode;
            generatedPages.push({ componentName, route: page.route || '/' });
        }

        // Generate App.jsx with Routing
        const appJsx = `
import { Routes, Route } from 'react-router-dom';
${generatedPages.map(p => `import ${p.componentName} from './pages/${p.componentName}';`).join('\n')}

export default function App() {
  return (
    <Routes>
${generatedPages.map(p => `      <Route path="${p.route}" element={<${p.componentName} />} />`).join('\n')}
    </Routes>
  );
}
`;
        files['src/App.jsx'] = appJsx.trim();

        // Add static files
        files['src/index.css'] = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`;

        files['README.md'] = `# Generated Website

This project was generated by the AI Website Builder.

## Setup

\`\`\`bash
npm install
npm run dev
\`\`\`
`;

        // Create ZIP
        const zipBuffer = await createZip(files, project.name);

        // Return as base64
        res.json({
            filename: `${project.name.replace(/\s+/g, '-').toLowerCase()}.zip`,
            data: zipBuffer.toString('base64')
        });
    } catch (error) {
        next(error);
    }
});

export default router;
